trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    shopt -s extglob dotglob
    mkdir helics
    mv !(helics) helics
    shopt -u dotglob
  displayName: 'Move helics-ns3 module files into subfolder'

- script: |
    sudo apt-get install -y libboost-dev libboost-signals-dev libboost-test-dev libboost-program-options-dev libboost-filesystem-dev libboost-system-dev libboost-date-time-dev libboost-timer-dev libboost-chrono-dev libzmq5-dev ninja-build
  displayName: 'Apt install required Boost and ZeroMQ libraries'

- script: |
    git clone https://github.com/GMLC-TDC/HELICS-src
    cd HELICS-src
    mkdir build
    cd build
    cmake -GNinja ../ -DBUILD_HELICS_TESTS=OFF -DBUILD_HELICS_EXAMPLES=OFF
    ninja
    ninja install
  displayName: 'Install HELICS'

- script: hg clone http://code.nsnam.org/ns-3-dev/
  displayName: 'Clone latest ns-3'

- script: |
    mv helics ns-3-dev/contrib
    cd ns-3-dev
    ./waf configure --disable-werror --with-helics=/usr/local --enable-modules=helics --enable-examples --enable-tests
  displayName: 'Configure ns-3'

- script: |
    cd ns-3-dev
    ./waf build
  displayName: 'Build ns-3'