trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-get install -y libboost-dev libboost-signals-dev libboost-filesystem-dev libboost-system-dev libboost-date-time-dev libboost-timer-dev libboost-chrono-dev libzmq5-dev
  displayName: 'Apt install required Boost and ZeroMQ libraries'

- script: |
    shopt -s extglob dotglob
    mkdir helics
    mv !(helics) helics
    shopt -u dotglob
  displayName: 'Copy helics-ns3 module files into a subfolder'

- script: hg clone http://code.nsnam.org/ns-3-dev/
  displayName: 'Clone ns-3'

- script: |
    mv helics ns-3-dev/contrib
    cd ns-3-dev
    ./waf configure --disable-werror
  displayName: 'Configure ns-3'

- script: |
    cd ns-3-dev
    ./waf build
  displayName: 'Build ns-3'

- script: echo $PWD
  displayName: 'Check pwd after another inline script executes'